# Thank you ChatGPT

#!/usr/bin/env python3
"""
img2header.py — Convert images to 1-bit bitmaps and emit a C++ header.

Packing:
  • Row-major, left->right then top->bottom.
  • MSB-first within each byte (leftmost pixel is bit 7).
  • Each row is padded to a whole number of bytes (no cross-row bit spill).
  • By default, bit=1 for black, bit=0 for white. Use --invert to flip.

Dependencies:
  pip install pillow
"""

from __future__ import annotations
import argparse
import re
from pathlib import Path
from typing import Iterable, Tuple, List
from datetime import datetime

from PIL import Image, ImageOps

# ---------- image handling ----------

def load_as_1bit(path: Path, threshold: int, dither: str, invert: bool) -> Image.Image:
    """Load an image file and return a 1-bit PIL Image."""
    img = Image.open(path).convert("RGBA")
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    img = Image.alpha_composite(bg, img).convert("L")

    if dither == "fs":
        img1 = img.convert("1")  # Floyd–Steinberg
    else:
        # Threshold: > threshold -> white (255), else black (0)
        img1 = img.point(lambda p: 255 if p > threshold else 0, mode="1")

    if invert:
        # Invert 1-bit (0 <-> 255)
        img1 = img1.point(lambda p: 0 if p else 255, mode="1")

    return img1

def pack_bits_row_major(img1: Image.Image) -> bytes:
    """
    Pack a 1-bit image into bytes:
      - MSB-first within each byte.
      - Row-major.
      - Pad end of each row to byte boundary with 0s.
    Bit value is 1 when the pixel is 'on' (black in the default pipeline).
    """
    assert img1.mode == "1"
    w, h = img1.width, img1.height
    pixels = img1.load()
    out = bytearray()
    for y in range(h):
        byte = 0
        bit_count = 0
        for x in range(w):
            # In PIL '1' mode: 0=black, 255=white
            bit = 1 if pixels[x, y] == 0 else 0
            byte = (byte << 1) | bit
            bit_count += 1
            if bit_count == 8:
                out.append(byte)
                byte = 0
                bit_count = 0
        if bit_count:  # pad the remainder of the row
            out.append(byte << (8 - bit_count))
    return bytes(out)

# ---------- C++ header emission ----------

IDENT_RX = re.compile(r'[^a-zA-Z0-9_]')
def sanitize_identifier(name: str) -> str:
    ident = IDENT_RX.sub('_', name)
    if not ident or ident[0].isdigit():
        ident = '_' + ident
    return ident

def unique_identifiers(basenames: Iterable[str]) -> List[str]:
    seen = {}
    result = []
    for base in basenames:
        ident = sanitize_identifier(base)
        if ident not in seen:
            seen[ident] = 1
            result.append(ident)
        else:
            idx = seen[ident]
            seen[ident] = idx + 1
            result.append(f"{ident}_{idx}")
    return result

def format_c_array(name: str, data: bytes, w: int, h: int) -> str:
    # 12 bytes per line for readability
    hex_bytes = [f"0x{b:02X}" for b in data]
    lines = []
    per_line = 12
    for i in range(0, len(hex_bytes), per_line):
        lines.append("    " + ", ".join(hex_bytes[i:i+per_line]))
    body = ",\n".join(lines)
    return (
        f"// {name} - {w}x{h} px, 1-bit, MSB-first, row-padded; 1=black, 0=white\n"
        f"static const uint8_t {name}[] = {{\n{body}\n}};\n"
    )

def write_header(output: Path, entries: List[Tuple[str, bytes, int, int]]) -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    with output.open("w", newline="\n") as f:
        f.write("// Auto-generated by img2header.py on " + ts + "\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write("namespace bitmaps{\n")
        for name, data, w, h in entries:
            f.write(format_c_array(name, data, w, h))
            f.write("\n")
        f.write("}\n")

# ---------- main ----------

IMAGE_EXTS = {".png", ".bmp", ".jpg", ".jpeg", ".gif", ".tif", ".tiff", ".pbm", ".pgm", ".ppm"}

def find_images(root: Path) -> List[Path]:
    return [p for p in sorted(root.iterdir()) if p.is_file() and p.suffix.lower() in IMAGE_EXTS]

def main() -> None:
    ap = argparse.ArgumentParser(description="Convert images to 1-bit and emit a C++ header of uint8_t arrays.")
    ap.add_argument("input_dir", type=Path, help="Folder containing images.")
    ap.add_argument("output_header", type=Path, help="Path to write the .h file.")
    ap.add_argument("--threshold", type=int, default=128, help="Threshold 0..255 used when not dithering (default 128).")
    ap.add_argument("--dither", choices=["none", "fs"], default="none", help="Dithering: none or Floyd–Steinberg (fs).")
    ap.add_argument("--invert", action="store_true", help="Set bits for white instead of black.")
    args = ap.parse_args()

    imgs = find_images(args.input_dir)
    if not imgs:
        raise SystemExit("No images found in the input directory with supported extensions.")

    basenames = [p.stem for p in imgs]
    idents = unique_identifiers(basenames)

    entries: List[Tuple[str, bytes, int, int]] = []
    for path, ident in zip(imgs, idents):
        img1 = load_as_1bit(path, threshold=args.threshold, dither=args.dither, invert=args.invert)
        packed = pack_bits_row_major(img1)
        entries.append((ident, packed, img1.width, img1.height))

    args.output_header.parent.mkdir(parents=True, exist_ok=True)
    write_header(args.output_header, entries)

if __name__ == "__main__":
    main()
