
[platformio]
build_cache_dir = buildCache/

[env:templog-esp-s3]
platform = espressif32
board = templog-v1
board_build.arduino.memory_type = qio_qspi
framework = arduino
monitor_speed = 115200
build_unflags = 
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17
build_flags = 
	-DCORE_DEBUG_LEVEL=ESP_LOG_ERROR
	-DBOARD_HAS_NO_PSRAM
    -std=gnu++20
lib_deps = zinggjm/GxEPD2@^1.6.4

extra_scripts = pre:extra_script.py
