
[platformio]
build_cache_dir = buildCache/

[env:templog-esp-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
board = templog-v1
board_build.arduino.memory_type = qio_qspi
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
build_flags = 
	-DCORE_DEBUG_LEVEL=ESP_LOG_ERROR
	-DBOARD_HAS_NO_PSRAM
lib_deps = zinggjm/GxEPD2@^1.6.4

extra_scripts = pre:extra_script.py
